version: "3.9"

services:
  app:
    image: python:3.12
    container_name: app
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "587:587"
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        alembic upgrade head &&
        python main.py
      "

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server"]
    restart: unless-stopped

volumes:
  pg_data:
  redis_data:
