"""add user role

Revision ID: 7ab1d4939112
Revises: 1db2ac5b6820
Create Date: 2025-06-15 13:12:35.298586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab1d4939112'
down_revision: Union[str, None] = '1db2ac5b6820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userrole AS ENUM ('USER', 'ADMIN')")
    op.add_column('users', sa.Column(
        'role',
        sa.Enum('USER', 'ADMIN', name='userrole'),
        nullable=False
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
